### ISSUE TITLE
Licenses with AND and OR

### ISSUE THREAD

**Issue by possani** [pivotal/LicenseFinder#728] opened 2020-05-12 12:48 UTC
Hello guys,

I am creating a gitlab-ci job and adding a set of default permitted licenses to it, but the number of combinations possible makes it not practical. What do I mean?

Let's say I approve MIT and CC0-1.0, I would expect LicenseFinder to accept also (MIT OR anything) and (MIT AND CC0-1.0), but this is not the current behavior.

Any suggestion for the scenario described above?

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-12 20:55
Hi @possani ! Would it be possible to show an example of current and desired output? At first glance I am not sure we would be able to make a change for this. LF does not make decisions on what is permissible of not. We rely on individuals to create a decisions file. The issue is not knowing more context about the licenses for a dependency. For example, if we had two dependencies with the same name but different licenses, we cannot assume they are both approved as one could be Go and one could be Ruby. I think a more detailed example can outlined desired state here.

The logic you described does make sense but I think I just need to understand the use case a bit better and what commands you are running. Thanks!

**Comment by possani** [comment] 2020-05-12 21:24
Hi @xtreme-shane-lattanzio, thank you for your reply.

After running:

license_finder permitted_licenses add "MIT"
license_finder permitted_licenses add "CC0-1.0"
license_finder permitted_licenses add "CC-BY-4.0"

I would not expect to see:

 Dependencies that need approval:
 @fortawesome/free-regular-svg-icons, 5.13.0, "(CC-BY-4.0 AND MIT)"
 store2, 2.11.1, "(MIT OR GPL-3.0)"
 type-fest, 0.11.0, "(MIT OR CC0-1.0)"

**Comment by rhuitl** [comment] 2020-05-14 00:09
I would like the same feature. Happens with a few NPM packages because in `package.json` SPDX expressions can be used: https://docs.npmjs.com/files/package.json#license. Another example for this: https://github.com/domenic/path-is-inside/blob/master/package.json

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-14 16:33
@possani Thanks for the clarification. This sounds like a good change. I thought you meant that they appeared on different lines but if it is like your example, we could have some kind of logic to evaluate those versions. If you want to make a PR regarding this we would be happy to look over it.

I also know there are other SPDX related issues/PRs from the past such as https://github.com/pivotal/LicenseFinder/pull/289/files that could be expanded upon. Not sure if they have additional context to help here.

**Comment by possani** [comment] 2020-05-19 13:30
I honestly don't have any experience with Ruby but will have a look at that.

**Comment by benlangfeld** [comment] 2020-12-08 18:18
Looks like this was closed by #755. Can you confirm @possani ?

**Comment by possani** [comment] 2020-12-08 18:22
Yes, this issue can be closed. Thank you, @nicolamarella!

**Closed** 2020-12-08 18:23 UTC
Labels: unscheduled
