### ISSUE TITLE
Trailing whitespace in file

### ISSUE THREAD

**Issue by hlascelles** [pivotal/LicenseFinder#837] opened 2021-06-17 15:59 UTC
We have noticed the yaml file gains trailing whitespace when using the CLI.

If a dev then opens it in an IDE that automatically removes trailing whitespace we see diffs.

![image](https://user-images.githubusercontent.com/299102/122432508-492daa80-cf8d-11eb-8824-cc07c85ff470.png)

Should we make sure the output has no trailing whitespace?

**Comment by xtreme-shane-lattanzio** [comment] 2021-07-06 15:19
@hlascelles I think it should be fine to fix this. If you want to make a PR to remove this and make sure tests still pass, I can take a look. Not sure what is causing the random spaces lol

**Comment by per1234** [comment] 2021-09-06 14:03
Duplicate of https://github.com/pivotal/LicenseFinder/issues/802

**Closed** 2022-07-06 17:22 UTC
Labels: unscheduled
