### ISSUE TITLE
licensefinder 3.0.1 throws a big error

### ISSUE THREAD

**Issue by slackersoft** [pivotal/LicenseFinder#322] opened 2017-07-20 20:47 UTC
I just installed license finder in ruby 2.2.7 globally and tried to run it in a newish Scala project and got the following error. It looks like a SyntaxError in the npm dependency manager.

```bash
 2017-07-20 13:36:17 ☆ |ruby-2.2.7| Queen in ~/<repo>
± gv+mh |master S:1 U:3 ✗| → license_finder help
/Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:9: syntax error, unexpected '.' (SyntaxError)
      top_level_deps = npm_json['dependencies']&.values || []
                                                 ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:13: syntax error, unexpected '.'
          package_json[group]&.keys&.include? dep['name']
                               ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:59: syntax error, unexpected '.'
...+ flatten(dep['dependencies']&.values&.map {|inner_dep| inne...
...                               ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:59: syntax error, unexpected ')', expecting '}'
...ep['groups']; inner_dep} || [])}
...                               ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:81: syntax error, unexpected '.'
...(dep_matches, 'dependencies')&.values&.map {|d| d['name']} |...
...                               ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:93: syntax error, unexpected '.'
      dep_matches.map {|m| m[key]}.reject(&:nil?).uniq&.first
                                                        ^
/Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_managers/npm.rb:95: syntax error, unexpected keyword_end, expecting '}'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/package_manager.rb:91:in `<top (required)>'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder/core.rb:6:in `<top (required)>'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/lib/license_finder.rb:9:in `<top (required)>'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/gems/license_finder-3.0.1/bin/license_finder:3:in `<top (required)>'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/bin/license_finder:23:in `load'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/bin/license_finder:23:in `<main>'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pivotal/.rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kdykeman** [comment] 2017-07-20 22:26
Thanks for the issue report @slackersoft!
There were clearly some hiccups with the 3.0.1 release mostly associated with updated to handling npm's json output. There's been a couple of re-works of npm handling post 3.0.1. I'll verify that this will be addressed in upcoming 3.0.2 release.

**Comment by maxmeyer** [comment] 2017-07-26 19:46
@kdykeman I think this is a duplicate of #311. @slackersoft Is using Ruby 2.2 which does not support the given syntax.

**Comment by ryanmattcollins** [comment] 2017-07-27 15:54
Hi @slackersoft, we should have resolved this issue as part of the rewrite we did in #319. Safe accessors have been removed in LicenseFinder 3.0.2. Closing this issue for now.

**Closed by ryanmattcollins** 2017-07-27 15:54 UTC
