### ISSUE TITLE
Support node dependency groups

### ISSUE THREAD

**Issue by taavo** [pivotal/LicenseFinder#113] opened 2014-09-22 18:45 UTC
Currently LicenseFinder is [punting](https://github.com/pivotal/LicenseFinder/blob/ad14c838e0d34c3941c3e973820b977206464b10/lib/license_finder/package_managers/npm_package.rb#L32) on the existence of npm dependency groups (e.g. "dependencies" vs "devDependencies"). It would be great to be able to exclude npm devDependencies the same way you can exclude bundler groups.

cc @nertzy

**Comment by mainej** [comment] 2015-06-23 05:31
Fixed by #152.

**Closed by mainej** 2015-06-23 05:31 UTC

**Comment by nkoterba** [comment] 2015-07-29 17:27
So perhaps I'm missing something but I don't see how #152 addresses this question.

I'd like to EXCLUDE `devDependencies` from LicenseFinder when crawling my npm-based directories.

However, the "fix" in #152 appear to always include both `dependencies` and `devDependencies`.

Am I missing some configuration item or command line argument?

**Comment by mainej** [comment] 2015-07-30 01:27
@nkoterba Have you run `license_finder ignored_groups add devDependencies` followed by `license_finder report`? If that's not working, you've found a bug.  A minimal package.json which reproduces the problem would help.

**Comment by nkoterba** [comment] 2015-07-30 01:51
@mainej Just verified that adding `devDependencies` as an ignored group does **not** filter out dev packages.

Keep in mind this is with npm/node.  According to the README.md, `ignored_groups` is only supported with Bundler.

Not sure if the documentation is correct or outdated.

Here's a simple package.json file that should show the issues:
```javascript
{
  "name": "test_ignored",
  "version": "1.0.0",
  "description": "Testing Ignored Groups with License_Finder",
  "dependencies": {
    "angular": "^1.4.3"
  },
  "devDependencies": {
    "gulp-rename": "^1.2.2"
  },
  "license": "ISC"
}
```

Here's what my `dependency_decisions.yml` file looks like after I ran the command you suggested above:
```javascript
---
- - :ignore_group
  - devDependencies
  - :who: 
    :why: 
    :when: 2015-07-30 01:49:51.659344000 Z
```

And here's my output:
```javascript
nk-mbp:webclient a$ license_finder
..........Dependencies that need approval:
angular, 1.4.3, MIT
gulp-rename, 1.2.2, MIT
```

If working, I believe we should only see `angular` there.

**Comment by mainej** [comment] 2015-07-30 02:37
hmm.... @LukeWinikates any thoughts on this?

**Comment by mainej** [comment] 2015-07-30 03:01
Actually, @LukeWinikates maybe there's no problem.  @nkoterba, #152 hasn't been released to Rubygems yet.  Does that explain things, or are you running off master from GitHub?

@flavorjones is it time for another version bump?

**Comment by nkoterba** [comment] 2015-07-30 14:28
@mainej Yes, I'm using the RubyGems version.

It sounds like it may just be best to use the GitHub version until 2.0.5 is released to RubyGems.

**Comment by LukeWinikates** [comment] 2015-07-30 17:44
@nkoterba I think you'll have success with the Github version. We're using it on my current project and successfully ignoring our `devDependencies`. Let me know if it doesn't work for you.

Thanks for pointing out the stale note in the README about Bundler being the only package manager with 'group' support.

**Comment by nkoterba** [comment] 2015-08-01 19:22
@LukeWinikates I can confirm that the Github version **does** work ignoring `devDependencies`.

Thanks!
