### ISSUE TITLE
No dependencies recognized for go 1.14

### ISSUE THREAD

**Issue by faraonc** [pivotal/LicenseFinder#740] opened 2020-05-27 22:54 UTC
`license_finder` reports no dependencies recognized if `go` in `go.mod` is set to 1.14

Sample `go.mod`
```
module github.com/foo/foo-service

go 1.14

require github.com/stretchr/testify v1.5.1
```

Sample `go.sum`
```
github.com/davecgh/go-spew v1.1.0 h1:ZDRjVQ15GmhC3fiQ8ni8+OwkZQO4DARzQgrnXU1Liz8=
github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
github.com/pmezard/go-difflib v1.0.0 h1:4DBwDE0NGyQoBHbLQYPwSUPoCMWR5BEzIk/f1lZbAQM=
github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZNVY4sRDYZ/4=
github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
github.com/stretchr/testify v1.5.1 h1:nOGnQDM7FYENwehXlg/kFVnos3rEvtKTjRvOWSzb6H4=
github.com/stretchr/testify v1.5.1/go.mod h1:5W2xD1RspED5o8YsWQXVCued0rvSQ+mT+I5cxcmMvtA=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405/go.mod h1:Co6ibVJAznAaIkqp8huTwlJQCZ016jof/cbN4VW5Yz0=
gopkg.in/yaml.v2 v2.2.2 h1:ZCJp+EgiOT7lHqUV2J862kp8Qj64Jo6az82+3Td9dZw=
gopkg.in/yaml.v2 v2.2.2/go.mod h1:hI93XBmqTisBFMUTm0b8Fm+jr3Dg1NNxqwp+5A1VGuI=

```

```bash
$ license_finder
LicenseFinder::GoModules: is active

No dependencies recognized!
```

If I used the docker image v6.4.0 in GitLab CI as image to run the job, then I would get the following `unknown` license type.
```bash
/bin/bash -lc license_finder action_items -p
 mesg: ttyname failed: Inappropriate ioctl for device
 LicenseFinder::GoModules: is active
 Dependencies that need approval:
 github.com/stretchr/testify, v1.5.1, unknown
```

If I update `go.mod` to `go 1.13`, then `license_finder` is able to find the dependencies for approval.

```bash
$ license_finder
LicenseFinder::GoModules: is active

Dependencies that need approval:
github.com/davecgh/go-spew, v1.1.0, unknown
github.com/pmezard/go-difflib, v1.0.0, "New BSD"
github.com/stretchr/objx, v0.1.0, MIT
github.com/stretchr/testify, v1.5.1, MIT
gopkg.in/check.v1, v0.0.0-20161208181325-20d25e280405, "Simplified BSD"
gopkg.in/yaml.v2, v2.2.2, "Apache 2.0, MIT"
```

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-28 14:23
Hey @faraonc! This is an interesting one. So it looks like the go modules package manager triggers on if a go.sum file exists. That is why when you just create a go.mod file, it says no package managers active.

I'm guessing why your CI reports something is that there is a go.sum file in there. Would you be able to share that as well? Then we will be able to experiment with different versions of go mod to see what is happening.

One note is that the installed version of go on the docker image is 1.13.3. I wonder if some kind of format changed in 1.14. If so, we will need to build in some kind of compatibility parsing. 

Let me know if you can get my a more reproducible example with a go.sum :)

**Comment by faraonc** [comment] 2020-05-28 15:46
> Hey @faraonc! This is an interesting one. So it looks like the go modules package manager triggers on if a go.sum file exists. That is why when you just create a go.mod file, it says no package managers active.
> 
> I'm guessing why your CI reports something is that there is a go.sum file in there. Would you be able to share that as well? Then we will be able to experiment with different versions of go mod to see what is happening.
> 
> One note is that the installed version of go on the docker image is 1.13.3. I wonder if some kind of format changed in 1.14. If so, we will need to build in some kind of compatibility parsing.
> 
> Let me know if you can get my a more reproducible example with a go.sum :)

I have updated the the issue above to include the `go.sum`.

There was a `go.sum` when it was ran in 1.14 locally (go 1.14.3)

I was thinking it might have something to do with an environment variable when it ran in the CI using Docker. I did not look in detail in the codebase, but I might when I get the chance.

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-28 16:16
The file to look at for functionality is https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/package_managers/go_modules.rb

When running prepare commands, we do run go mod tidy which will clear out the sum file if things are unused. Locally with go version 1.13.3 I managed to reproduce your results with ` github.com/stretchr/testify, v1.5.1, unknown
`

I cannot seem to get the full results that you outlined after that but that could just be because of the actual project missing locally. I am not convinced that this is a version specific issue. To be honest, I am not a Go expert by any means so I wonder if Gomod is doing something weird with the go version in the .mod file when running one of the commands.

**Comment by faraonc** [comment] 2020-05-28 16:45
> The file to look at for functionality is https://github.com/pivotal/LicenseFinder/blob/master/lib/license_finder/package_managers/go_modules.rb
> 
> When running prepare commands, we do run go mod tidy which will clear out the sum file if things are unused. Locally with go version 1.13.3 I managed to reproduce your results with `github.com/stretchr/testify, v1.5.1, unknown`
> 

This is what we are seeing in the CI, as it is running the Docker image which is using the go version specified in the [Dockerfile](https://github.com/pivotal/LicenseFinder/blob/master/Dockerfile#L86), so I think the repro is good.

> I cannot seem to get the full results that you outlined after that but that could just be because of the actual project missing locally. I am not convinced that this is a version specific issue. To be honest, I am not a Go expert by any means so I wonder if Gomod is doing something weird with the go version in the .mod file when running one of the commands.

It seems like they did change a bunch of stuff related to go modules on the major update https://golang.org/doc/go1.14. We might be missing a flag somewhere

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-28 18:51
We actually just made a PR to bump the golang version. I'm not sure if this is gonna fix this issue. I also still cannot reproduce the output you put last when changing the go.mod file to have 1.13 in it. Maybe the golang docker bump will shed some light!

**Comment by faraonc** [comment] 2020-05-28 18:54
I will keep you posted once the image is in DockerHub

**Comment by xtreme-shane-lattanzio** [comment] 2020-05-29 13:31
It looks like they change defaults in 1.14 from being `--mod=mod` to `--mod=vendor`. We had code that depended on this so we flipped the logic at the same time of this upgrade and will be fixed in the next release. https://github.com/pivotal/LicenseFinder/pull/743

**Comment by faraonc** [comment] 2020-06-01 22:27
I was able to verify this to work against `GitLab Enterprise Edition 12.10.6-ee` using 6.5.0 release.

Thank you so much!

**Closed** 2020-06-04 15:02 UTC
Labels: accepted
