### ISSUE TITLE
license_finder fails with error on npm projects

### ISSUE THREAD

**Issue by ghost** [pivotal/LicenseFinder#333] opened 2017-08-23 22:38 UTC
When I tried running `license_finder` on a Maven Java project it worked just fine, but when I tried running it on an NPM Javascript project it failed with an error which said "The process cannot access the file because it is being used by another process". I already made sure that no files were open in any other application or window. I also tried running it on several different NPM Javascript projects, but I got the same error for all of them. I'm running on a Windows 7 OS, with Ruby version 2.2.5. I'm copying and pasting the full error I get when I try to run `license_finder` on an NPM Javascript project below (again, this problem **only** occurs with NPM Javascript projects; Maven Java projects work just fine). Do you know what might be causing this problem and/or how to fix it?

```
The process cannot access the file because it is being used by another process.
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm.rb:39:in `npm_json': Comm
and 'npm list --json --long' failed to execute:  (RuntimeError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_managers/npm.rb:7:in `cur
rent_packages'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_manager.rb:60:in `current
_packages_with_relations'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_manager.rb:23:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_manager.rb:23:in `flat_ma
p'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/package_manager.rb:23:in `current
_packages'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/core.rb:63:in `current_packages'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/core.rb:58:in `decision_applier'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/lib/license_finder/cli/main.rb:82:in `report'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/license_finder-3.0.2/bin/license_finder:5:in `<top (required)>'
        from C:/Ruby22-x64/bin/license_finder:23:in `load'
        from C:/Ruby22-x64/bin/license_finder:23:in `<main>'
```

@kdykeman
@ryanmattcollins

**Comment by sschuberth** [comment] 2017-10-06 10:34
I came across the same issue when trying to make tests pass on Windows CI. The problem is with the code

https://github.com/pivotal/LicenseFinder/blob/841586d8014da8d2c7889c4cd5b8271d3666b180/lib/license_finder/package_managers/npm.rb#L20-L30

not working on Windows. I'm working on a fix for this as part of https://github.com/pivotal/LicenseFinder/pull/368.

**Comment by sschuberth** [comment] 2017-11-06 21:28
This should be fixed now that https://github.com/pivotal/LicenseFinder/pull/397 is merged.

**Closed** 2017-12-13 00:13 UTC
